"""
Django settings for Movie project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# For config.json file
# import json
# with open('config.json', 'r') as f:
#     config = json.load(f)

import environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# reading .env file
environ.Env.read_env()



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'django_filters',
    'recommendation',
    'home',
    'login_signup',
    'client',
    'movie_admin',
    'django.contrib.sites',  # This comes from django-allauth

    # This bellow app is provided by 'django-allauth'
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # providers (This also comes from django-allauth)
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'sweetify',

    'django_crontab',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



CRONJOBS = [
    ('*/2 * * * *', 'login_signup.cron.registration_expiry_check')
]





ROOT_URLCONF = 'Movie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Movie.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
        'init_command': 'SET foreign_key_checks = 0;',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

#STATIC_ROOT is the absolute path to where you want Django to put the static files that are collected using collectstatic. Your web server will serve static files from this directory.
STATIC_ROOT = os.path.join(BASE_DIR, env('STATIC_ROOT'))


# STATICFILES_DIRS is a list of directories where you want collectstatic to look when collecting the static files. If cannot include STATIC_ROOT or any subdirectory of it.
STATICFILES_DIRS = [
    # Static Files haru ko direcotry dekhako... i.e hamile static folder banako xau.. so tyo folder ko naam 'static' xa ... yo static folder ma sabbai static files haru xa
    os.path.join(BASE_DIR, env('STATICFILES_DIRS'))
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, env('MEDIA_ROOT'))

# Custom Django auth settings

AUTH_USER_MODEL = 'login_signup.User'

LOGIN_URL = 'login'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert2'

# SMTP Configuration                                          # yo tala ko chai Password Reset mail send garna ko lagi chaine kura haru ho

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # yo line ma j xa tei nai lekna parxa
EMAIL_HOST = env('EMAIL_HOST')  # gmail ko id vayera gmail.com gareko
EMAIL_PORT = env('EMAIL_PORT')  # Since we are using TLS, so we use EMAIL_PORT = 587
EMAIL_USE_TLS = True  # TLS lai TRUE garne
EMAIL_HOST_USER = env('EMAIL_HOST_USER')  # jun gmail batw reset email pathaune ho tyo email ID lekhinxa
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

SITE_ID = env('SITE_ID')  # This is for django_site database table.
LOGIN_REDIRECT_URL = "/"  # Login vayesakey pachi kata jani vanera ho


# views.py ma use vako message tags haru ko lagi and colorful msg auna ko lagi tala ko code imp cha.
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

CSRF_FAILURE_VIEW = 'login_signup.views.logoutall'